### ISSUE TITLE
[Bug]:  ray mode, NameError: name 'OPENCC_CONVERTER' is not defined

### ISSUE THREAD

**Issue by simplew2011** [modelscope/data-juicer#210]
### Before Reporting 报告之前

- [X] I have pulled the latest code of main branch to run again and the bug still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully and no error occurred during the installation process. (Otherwise, we recommend that you can ask a question using the Question template) 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引，并且在安装过程中没有错误发生。（否则，我们建议您使用Question模板向我们进行提问）

### Search before reporting 先搜索，再报告

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar bugs. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的bug报告。

### OS 系统

ubuntu

### Installation Method 安装方式

 from source

### Data-Juicer Version Data-Juicer版本

v0.1.3

### Python Version Python版本

3.8

### Describe the bug 描述这个bug

chinese_convert_mapper算子在ray模式下报错

### To Reproduce 如何复现

`dj-process --config demos/process_on_ray/configs/demo.yaml`

### Configs 配置信息

```
# Process config example for dataset

# global parameters
project_name: 'ray-demo'
executor_type: 'ray'
dataset_path: './demos/process_on_ray/data/demo-dataset.json'  # path to your dataset directory or file
ray_address: 'auto'                     # change to your ray cluster address, e.g., ray://<hostname>:<port>
export_path: './outputs/demo/demo-processed'

# process schedule
# a list of several process operators with their arguments
process:
  # Filter ops
  - alphanumeric_filter:                                    # filter text with alphabet/numeric ratio out of specific range.
      tokenization: false                                     # Whether to count the ratio of alphanumeric to the total number of tokens.
      min_ratio: 0.0                                          # the min ratio of filter range
      max_ratio: 0.9                                          # the max ratio of filter range

  - chinese_convert_mapper:                                 # convert Chinese between Traditional Chinese, Simplified Chinese and Japanese Kanji.
      mode: 't2s' 
```

### Logs 报错日志

```
  File "/home/wzp/code/LLMData/open_source/0220/data-juicer/data_juicer/ops/mapper/chinese_convert_mapper.py", line 56, in process
    sample[self.text_key] = OPENCC_CONVERTER.convert(sample[self.text_key])
NameError: name 'OPENCC_CONVERTER' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/loguru/_handler.py", line 204, in emit
    self._queue.put(str_record)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/multiprocessing/queues.py", line 362, in put
    obj = _ForkingPickler.dumps(obj)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'ray.exceptions.RayTaskError(NameError)'>: attribute lookup RayTaskError(NameError) on ray.exceptions failed
--- End of logging error ---
```

**Comment by simplew2011** [comment]
另一个问题

```
project_name: 'ray-demo'
executor_type: 'ray'
dataset_path: '/home/wzp/code/LLMData/open_source/0220/data-juicer/demos/process_on_ray/data/demo-dataset.json'  # path to your dataset directory or file
ray_address: 'auto'                     # change to your ray cluster address, e.g., ray://<hostname>:<port>
export_path: './outputs/demo/demo-processed'

# process schedule
# a list of several process operators with their arguments
process:
  # Filter ops
  - alphanumeric_filter:                                    # filter text with alphabet/numeric ratio out of specific range.
      tokenization: false                                     # Whether to count the ratio of alphanumeric to the total number of tokens.
      min_ratio: 0.0                                          # the min ratio of filter range
      max_ratio: 0.9                                          # the max ratio of filter range
  - average_line_length_filter:                             # filter text with the average length of lines out of specific range.
      min_len: 10                                             # the min length of filter range
      max_len: 10000                                          # the max length of filter range

```
- 我在head机器上启动：
```
ray start --head --node-ip-address="192.168.30.161" --port="6666"
```

- 在另一台机器上启动**work**节点：
```
ray start --address="192.168.30.161:6666"
```
```
ray status

======== Autoscaler status: 2024-02-20 11:55:52.635245 ========
Node status
---------------------------------------------------------------
Active:
 1 node_a50ae1ba11b3662bb36fa5cf5ac8cc9be7301603f521b92132c0743a
 1 node_a5cb7605e6ae9d776cb877d8c8322c9d54b615b1eefb1650b0227f72
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/224.0 CPU
 0.0/10.0 GPU
 0B/350.91GiB memory
 0B/154.38GiB object_store_memory

Demands:
 (no resource demands)
```
- 然后在host机器上执行
```
dj-process --config /home/wzp/code/LLMData/open_source/0220/data-juicer/demos/process_on_ray/configs/demo.yaml
```
- 会报错（不使用work节点，只有一个head节点是正常的）：
```
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 277, in <lambda>
  File "/home/simplew/miniconda3/envs/3.8.5/lib/python3.8/site-packages/ray/data/datasource/file_based_datasource.py", line 385, in _open_input_source
    file = filesystem.open_input_stream(path, buffer_size=buffer_size, **open_args)
  File "pyarrow/_fs.pyx", line 812, in pyarrow._fs.FileSystem.open_input_stream
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 113, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/home/wzp/code/LLMData/open_source/0220/data-juicer/demos/process_on_ray/data/demo-dataset.json'. Detail: [errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/site-packages/loguru/_handler.py", line 204, in emit
    self._queue.put(str_record)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/multiprocessing/queues.py", line 362, in put
    obj = _ForkingPickler.dumps(obj)
  File "/home/wzp/anaconda3/envs/python3.8/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'ray.exceptions.RayTaskError(FileNotFoundError)'>: attribute lookup RayTaskError(FileNotFoundError) on ray.exceptions failed
```

- 上面文件路径在head节点机器上，路径是正确的
- 有几个疑问：
    - ray cluster在加载原始数据时应该是在head节点上加载的吧，然后分发至多个work节点上作处理（平均分布？）
    - 各work节点上处理完后的结果是保存在每个work机器上的block么？

**Comment by pan-x-c** [comment]
非常抱歉没能及时回复

1. Ray 在加载数据时，如果不做特殊处理，默认是由所有节点一起加载的，而不是仅由 head 节点加载。如果给出的路径带有 `local://` 前缀，则每个节点会仅加载本地对应文件的数据；如果文件路径不带前缀，Ray 会认为文件位于NFS(Network File System)上，各个节点会自动读取该文件的不同分片。具体可参考 ray 的[数据读取文档](https://docs.ray.io/en/latest/data/loading-data.html)
2. 处理完成后的结果保存与数据加载同理，也是所有节点都会保存自己的数据，可以参考 ray 的 [数据保存文档](https://docs.ray.io/en/latest/data/saving-data.html)

当前仓库中的样例是基于 NFS 的。如果没有 NFS，需要自己手动将数据文件分片后保存到不同机器上的相同路径上，并在读取和写入的路径前加上 `local://`，我们在后续的更新中也会加入对应数据自动分发的支持
