### ISSUE TITLE
是否可以修改依赖中的transformers版本，怀疑下面报错为依赖问题

### ISSUE THREAD

**Issue by baiyi-os** [modelscope/data-juicer#524]
### Before Asking 在提问之前

- [X] I have read the [README](https://github.com/alibaba/data-juicer/blob/main/README.md) carefully. 我已经仔细阅读了 [README](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md) 上的操作指引。

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking 先搜索，再提问

- [X] I have searched the Data-Juicer [issues](https://github.com/alibaba/data-juicer/issues) and found no similar questions. 我已经在 [issue列表](https://github.com/alibaba/data-juicer/issues) 中搜索但是没有发现类似的问题。

### Question

Traceback (most recent call last):
  File "/data/xinqiuqing/data-juicer/data_juicer/ops/base_op.py", line 60, in wrapper
    return method(samples, *args, **kwargs)
  File "/data/xinqiuqing/data-juicer/data_juicer/ops/mapper/generate_qa_from_text_mapper.py", line 113, in process_batched
    model, _ = get_model(self.model_key, rank, self.use_cuda())
  File "/data/xinqiuqing/data-juicer/data_juicer/utils/model_utils.py", line 807, in get_model
    MODEL_ZOO[model_key] = model_key(device=device)
  File "/data/xinqiuqing/data-juicer/data_juicer/utils/model_utils.py", line 377, in prepare_huggingface_model
    pipe = transformers.pipeline(task=pipe_task,
  File "/root/miniconda3/envs/xinqiuqing/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 1178, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "/root/miniconda3/envs/xinqiuqing/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 106, in __init__
    if self.prefix is not None:
AttributeError: 'TextGenerationPipeline' object has no attribute 'prefix'
generate_qa_from_text_mapper_process: 100%|##########| 129/129 [01:34<00:00,  1.36 examples/s]
2024-12-26 16:54:19 | INFO     | data_juicer.core.data:226 - [7/7] OP [generate_qa_from_text_mapper] Done in 95.495s. Left 0 samples.

### Additional 额外信息

这是我的配置yaml文件
project_name: 'test01'
dataset_path: 'data/test/' 
export_path: 'outputs/test/test.jsonl'
export_shard_size: 0
export_in_parallel: false
np: 4
suffixes: ['.txt']

process:
  # 对文本进行分片处理
  - text_chunk_mapper:
      max_len: 1000
      split_pattern: '\n\n'
      overlap_len: 200
      tokenizer: 'qwen2.5-72b-instruct'
      trust_remote_code: True
  # 删除链接，例如以 http 或 ftp 开头的
  - clean_links_mapper:
  # 删除 HTML 标签并返回所有节点的纯文本
  - clean_html_mapper:
  # 删除 TeX 文档的参考文献     
  - remove_bibliography_mapper:
  # 删除 TeX 文档头，例如标题、章节数字/名称等  
  - remove_header_mapper:
      drop_no_head: true
  # 删除样本中的重复句子        
  - remove_repeat_sentences_mapper:
      lowercase: false
      ignore_special_character: true
      min_repeat_sentence_length: 2
  # 从文本中生成问答对 
  - generate_qa_from_text_mapper:
      hf_model: 'impira/layoutlm-document-qa'
      output_pattern: null
      enable_vllm: false
      model_params: {}
      sampling_params: {}
      mem_required: '10GB

**Comment by baiyi-os** [comment]
大家的transformers版本是多少

**Comment by HYLcool** [comment]
嗨 @baiyi-os ，感谢你使用Data-Juicer！

经过我们检查与复现后发现，你在使用`generate_qa_from_text_mapper `算子时传入的模型'impira/layoutlm-document-qa'不太适用于当前算子面向的”文本生成“场景（从文本中提取并生成QA对），你可以从huggingface上挑选更合适的模型来放入这个模型完成任务（如Qwen，或者算子的默认模型）

在transformers库中，如果某个模型不是”可生成“的模型，那它就不会有prefix这个属性，可参考这部分代码：https://github.com/huggingface/transformers/blob/5cabc75b4bdb2e67935f7195f901afd150746eb3/src/transformers/pipelines/base.py#L930

如还有其他问题，可随时联系~

**Comment by baiyi-os** [comment]
感谢您的回复

**Comment by HYLcool** [comment]
Close this stale issue.
